[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SFIArtificialStockMarket = "92ea773a-4c2e-4dd1-b9ab-722396848ce4"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
VL_LimitOrderBook = "aaf583bd-e1f6-46ea-b02f-a6ceb51252d5"
